// src/ListOfThings/ContentChooser.tsx
import React from 'react';

export function ContentChooser({
  resetSidePanel,
  showSearchableList,
}: {
  resetSidePanel: () => void;
  showSearchableList: () => void;
}) {
  return (
    <menu>
      <button onClick={resetSidePanel}>Reset side panel</button>
      <button onClick={showSearchableList}>Display searchable list</button>
    </menu>
  );
}

// src/ListOfThings/ContentChooser.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { mapStores } from 'pinia';
import { useDynamicContentStore } from './dynamicContentStore';

export default defineComponent({
  name: 'ContentChooser',
  computed: {
    ...mapStores(useDynamicContentStore),
  },
});
</script>

<template>
  <menu>
    <button @click="dynamicContentStore.resetSidePanel">Reset side panel</button>
    <button @click="dynamicContentStore.showSearchableList">Display seachable list</button>
  </menu>
</template>
